"""Tests for synthetic QA pair generation (RAG fine-tuning pipeline)."""
import json
import asyncio
import numpy as np
import pytest
from unittest.mock import patch, MagicMock
from pathlib import Path
import tempfile

from eeg_rag.rag.synthetic_qa import (
    QAPair,
    QABatch,
    SyntheticQAGenerator,
    _parse_qa_json,
    generate_qa_pairs_async,
)

SAMPLE_CHUNKS = [
    {
        "chunk_id": "chunk_001",
        "text": (
            "Alpha waves (8-13 Hz) are prominent during relaxed wakefulness with "
            "closed eyes. They are generated by thalamocortical circuits and are "
            "attenuated by eye opening or mental activity, a phenomenon known as "
            "alpha blocking or the Berger effect."
        ),
    },
    {
        "chunk_id": "chunk_002",
        "text": (
            "P300 is an event-related potential component observed approximately "
            "300 ms after an infrequent, task-relevant stimulus. It is maximal over "
            "parietal electrodes (Pz) and reflects cognitive processes including "
            "attention, working memory updating, and stimulus evaluation."
        ),
    },
]

MOCK_LLM_RESPONSE = json.dumps([
    {
        "question": "What frequency range defines alpha waves?",
        "answer": "Alpha waves are defined as oscillations in the 8-13 Hz range.",
        "type": "factoid",
    },
    {
        "question": "Why do alpha waves attenuate when eyes open?",
        "answer": "Alpha attenuation (Berger effect) occurs because eye opening or mental activity disrupts thalamocortical circuit synchrony.",
        "type": "causal",
    },
    {
        "question": "What circuits generate alpha waves?",
        "answer": "Alpha waves are generated by thalamocortical circuits.",
        "type": "factoid",
    },
])


class TestQAPair:
    def test_pair_id_is_deterministic(self):
        p1 = QAPair(question="Q?", answer="A.", chunk_id="c1", chunk_text="text")
        p2 = QAPair(question="Q?", answer="A.", chunk_id="c1", chunk_text="text")
        assert p1.pair_id == p2.pair_id

    def test_different_questions_different_ids(self):
        p1 = QAPair(question="Q1?", answer="A.", chunk_id="c1", chunk_text="text")
        p2 = QAPair(question="Q2?", answer="A.", chunk_id="c1", chunk_text="text")
        assert p1.pair_id != p2.pair_id

    def test_to_dict_excludes_embedding(self):
        p = QAPair(question="Q?", answer="A.", chunk_id="c1", chunk_text="text")
        p.question_embedding = np.zeros(384, dtype=np.float32)
        d = p.to_dict()
        assert "question_embedding" not in d
        assert d["question"] == "Q?"
        assert d["chunk_id"] == "c1"

    def test_pair_id_length(self):
        p = QAPair(question="Q?", answer="A.", chunk_id="x", chunk_text="t")
        assert len(p.pair_id) == 16


class TestQABatch:
    def _make_batch(self, n=4):
        pairs = []
        for i in range(n):
            p = QAPair(
                question=f"Q{i}?",
                answer=f"A{i}.",
                chunk_id=f"chunk_{i % 2}",
                chunk_text="text",
            )
            p.question_embedding = np.random.rand(384).astype(np.float32)
            pairs.append(p)
        return QABatch(pairs=pairs, stats={"total": n})

    def test_total_pairs(self):
        batch = self._make_batch(6)
        assert batch.total_pairs == 6

    def test_pairs_for_chunk(self):
        batch = self._make_batch(4)
        assert len(batch.pairs_for_chunk("chunk_0")) == 2
        assert len(batch.pairs_for_chunk("chunk_1")) == 2
        assert batch.pairs_for_chunk("nonexistent") == []

    def test_get_question_embeddings_shape(self):
        batch = self._make_batch(4)
        matrix, ids = batch.get_question_embeddings()
        assert matrix.shape == (4, 384)
        assert len(ids) == 4

    def test_get_question_embeddings_no_embeddings(self):
        pairs = [QAPair(question="Q?", answer="A.", chunk_id="c", chunk_text="t")]
        batch = QABatch(pairs=pairs)
        matrix, ids = batch.get_question_embeddings()
        assert matrix.shape[0] == 0

    def test_to_jsonl(self):
        batch = self._make_batch(3)
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "out.jsonl"
            batch.to_jsonl(path)
            lines = path.read_text().strip().splitlines()
            assert len(lines) == 3
            obj = json.loads(lines[0])
            assert "question" in obj
            assert "chunk_id" in obj


class TestParseQAJson:
    def test_plain_json(self):
        raw = '[{"question":"Q?","answer":"A.","type":"factoid"}]'
        items = _parse_qa_json(raw)
        assert len(items) == 1
        assert items[0]["question"] == "Q?"

    def test_strips_markdown_fence(self):
        raw = "```json\n[{\"question\":\"Q?\",\"answer\":\"A.\",\"type\":\"factoid\"}]\n```"
        items = _parse_qa_json(raw)
        assert items[0]["answer"] == "A."

    def test_raises_on_no_array(self):
        with pytest.raises(ValueError):
            _parse_qa_json("This is not JSON at all.")

    def test_multiple_items(self):
        raw = MOCK_LLM_RESPONSE
        items = _parse_qa_json(raw)
        assert len(items) == 3


class TestSyntheticQAGenerator:
    def _make_gen(self):
        return SyntheticQAGenerator(
            llm_backend="ollama",
            n_questions_per_chunk=3,
            embed_model="all-MiniLM-L6-v2",
            inter_chunk_delay=0.0,
        )

    @patch("eeg_rag.rag.synthetic_qa._dispatch_llm", return_value=MOCK_LLM_RESPONSE)
    @patch("eeg_rag.rag.synthetic_qa.SyntheticQAGenerator._embed_texts")
    def test_generate_for_corpus_count(self, mock_embed, mock_llm):
        mock_embed.return_value = np.zeros((6, 384), dtype=np.float32)
        gen = self._make_gen()
        batch = gen.generate_for_corpus(SAMPLE_CHUNKS, show_progress=False)
        # 2 chunks × 3 questions each
        assert batch.total_pairs == 6

    @patch("eeg_rag.rag.synthetic_qa._dispatch_llm", return_value=MOCK_LLM_RESPONSE)
    @patch("eeg_rag.rag.synthetic_qa.SyntheticQAGenerator._embed_texts")
    def test_embeddings_assigned(self, mock_embed, mock_llm):
        mock_embed.return_value = np.ones((6, 384), dtype=np.float32)
        gen = self._make_gen()
        batch = gen.generate_for_corpus(SAMPLE_CHUNKS, show_progress=False)
        assert all(p.question_embedding is not None for p in batch.pairs)

    @patch("eeg_rag.rag.synthetic_qa._dispatch_llm", side_effect=RuntimeError("LLM down"))
    @patch("eeg_rag.rag.synthetic_qa.SyntheticQAGenerator._embed_texts")
    def test_llm_error_skips_chunk(self, mock_embed, mock_llm):
        mock_embed.return_value = np.zeros((0, 384), dtype=np.float32)
        gen = self._make_gen()
        batch = gen.generate_for_corpus(SAMPLE_CHUNKS, show_progress=False)
        assert batch.stats["errors"] == 2
        assert batch.total_pairs == 0

    @patch("eeg_rag.rag.synthetic_qa._dispatch_llm", return_value=MOCK_LLM_RESPONSE)
    @patch("eeg_rag.rag.synthetic_qa.SyntheticQAGenerator._embed_texts")
    def test_save_batch_creates_files(self, mock_embed, mock_llm):
        mock_embed.return_value = np.zeros((6, 384), dtype=np.float32)
        gen = self._make_gen()
        batch = gen.generate_for_corpus(SAMPLE_CHUNKS, show_progress=False)
        with tempfile.TemporaryDirectory() as tmp:
            paths = gen.save_batch(batch, tmp)
            assert Path(paths["jsonl"]).exists()
            assert Path(paths["embeddings"]).exists()
            assert Path(paths["chunk_ids"]).exists()
            assert Path(paths["stats"]).exists()

    @patch("eeg_rag.rag.synthetic_qa._dispatch_llm", return_value=MOCK_LLM_RESPONSE)
    @patch("eeg_rag.rag.synthetic_qa.SyntheticQAGenerator._embed_texts")
    def test_stats_keys(self, mock_embed, mock_llm):
        mock_embed.return_value = np.zeros((6, 384), dtype=np.float32)
        gen = self._make_gen()
        batch = gen.generate_for_corpus(SAMPLE_CHUNKS, show_progress=False)
        for key in ("total_chunks", "total_pairs", "errors", "avg_pairs_per_chunk"):
            assert key in batch.stats

    @patch("eeg_rag.rag.synthetic_qa._dispatch_llm", return_value=MOCK_LLM_RESPONSE)
    @patch("eeg_rag.rag.synthetic_qa.SyntheticQAGenerator._embed_texts")
    def test_question_types_preserved(self, mock_embed, mock_llm):
        mock_embed.return_value = np.zeros((6, 384), dtype=np.float32)
        gen = self._make_gen()
        batch = gen.generate_for_corpus([SAMPLE_CHUNKS[0]], show_progress=False)
        types = {p.question_type for p in batch.pairs}
        assert "factoid" in types or "causal" in types

    @patch("eeg_rag.rag.synthetic_qa._dispatch_llm", return_value=MOCK_LLM_RESPONSE)
    @patch("eeg_rag.rag.synthetic_qa.SyntheticQAGenerator._embed_texts")
    def test_async_wrapper(self, mock_embed, mock_llm):
        mock_embed.return_value = np.zeros((6, 384), dtype=np.float32)
        batch = asyncio.run(
            generate_qa_pairs_async(SAMPLE_CHUNKS, n_questions_per_chunk=3)
        )
        assert batch.total_pairs == 6
